export const InitialState = {
  isLoading: false,
  token: '',
  user: '',
  channel: '',
  imgLink: '',
  videoLink: '',
  events: [],
  celebrities: [],
  freeTrailers: [],
  proTrailers: [],
  freeImages: [],
  paidImges: [],
  channelEvents: [],
}
