export { default as Nav } from './Nav'
export { default as Slider } from './Slider'
export { default as Sidebar } from './Sidebar'
export { default as Featured } from './Featured'
export { default as WhatToWatch } from './WhatToWatch'
export { default as Explore } from './Explore'
export { default as CommingSoon } from './CommingSoon'
